base:
  project: SAHeart-project
  random_state: 42
  target_col: chd

data_source:
  s3_source: data_given/SAHeart.csv
  

load_data:
  raw_dataset_csv: data/raw/SAHeart.csv

split_data:
  train_path: data/processed/train_SAHeart.csv
  test_path: data/processed/test_SAHeart.csv
  test_size: 0.20

model_dir: saved_models
result_dir: 
  result_cross_check: result/cm.csv

reports:
  scores: report/scores.json
  roc: report/roc.json
  prc: report/prc.json
  auc: report/auc.json